apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:

  name: argo-applicationnew

  namespace: argocdn

spec:

  project: default

  source:
    
    repoURL: https://github.com/dyutis/argocdpoc.git
    
    targetRevision: HEAD

    path: k8s

  destination: 

    server: https://kubernetes.default.svc

    namespace: dyutiargonew

  syncPolicy:

    syncOptions:

    - CreateNamespace=true

    automated:

      selfHeal: true

      prune: true
