apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
  namespace: dyutiargo
  labels:
    app: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocdpod
        image: hello-world:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

