apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
  namespace: dyutiargonew
  labels:
    app: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocdpod
        image: springio/gs-spring-boot-docker
        imagePullPolicy: Always

